'CaptchaEU.CaptchaEU:OverrideConfigurationMixin':
  abstract: true
  ui:
    inspector:
      tabs:
        CaptchaEU:
          label: 'Captcha.eu'
          icon: 'resource://CaptchaEU.CaptchaEU/Icons/cpt-icon.svg'
          position: 15
      groups:
        config:
          label: i18n
          icon: 'resource://CaptchaEU.CaptchaEU/Icons/cpt-icon.svg'
          tab: CaptchaEU
  properties:
    overrideOptions:
      type: boolean
      defaultValue: false
      ui:
        label: i18n
        inspector:
          group: config
    overrideStartVerification:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideOptions ? false : true'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            placeholder: i18n
            allowEmpty: true
            multiple: false
            values:
              auto:
                label: 'Auto'
              focus:
                label: 'Focus'
              none:
                label: 'None'
    overrideKeys:
      type: boolean
      defaultValue: false
      ui:
        label: i18n
        inspector:
          group: config
    overridePublicKey:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideKeys ? false : true'
    overrideRestKey:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideKeys ? false : true'
