Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'CaptchaEU.CaptchaEU:Captcha':
            superTypes:
              - 'Neos.Form:FormElement'
            validators:
              - identifier: 'Neos.Flow:NotEmpty'
            renderingOptions:
              templatePathPattern: 'resource://CaptchaEU.CaptchaEU/Private/Form/Captcha.html'
              validationErrorTranslationPackage: CaptchaEU.CaptchaEU
            implementationClassName: CaptchaEU\CaptchaEU\FormElements\Captcha
  Neos:
    fusion:
      autoInclude:
        'CaptchaEU.CaptchaEU': true
    userInterface:
      translation:
        autoInclude:
          'CaptchaEU.CaptchaEU':
            - 'NodeTypes/*'

CaptchaEU:
  CaptchaEU:
    publicKey: 'add-your-site-key'
    restKey: 'add-your-secret-key'
